stuff

diff --git a/bin/oo b/bin/oo
--- a/bin/oo
+++ b/bin/oo
@@ -1,8 +1,7 @@
 #!/bin/zsh
-
 # Configuration based on username
 declare -A CONFIG
-CONFIG[christian.francia]="/Users/christian.francia/worknotes"
+CONFIG[christian.francia]="/Users/christian.francia/Projects/personal/notes"
 CONFIG[ctfrancia]="/Users/ctfrancia/Library/Mobile Documents/iCloud~md~obsidian/Documents/thoughts"
 
 current_user=$(whoami)
@@ -13,9 +12,9 @@ user_config=${CONFIG[$current_user]}
 # check if that users config exists
 if [ -z "$user_config" ]; then
     echo "Error: No configuration found for user $current_user"
-    exit 1
+    return 1 2>/dev/null || exit 1
 fi
 
 # cd to the user's config
 echo "Changing to $user_config"
-cd "$user_config" || { echo "Error: Unable to access $user_config"; exit 1; }
+cd "$user_config" || { echo "Error: Unable to access $user_config"; return 1 2>/dev/null || exit 1; }
